package entity;
// Generated 24 janv. 2020 17:40:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name = "personne", catalog = "getwirelessdb")
public class Personne implements java.io.Serializable {

	private Integer id;
	private Date dateNaissance;
	private String loisir;
	private String nom;
	private String prenom;
	private String sexe;
	private String ville;

	public Personne() {
	}

	public Personne(Date dateNaissance, String loisir, String nom, String prenom, String sexe, String ville) {
		this.dateNaissance = dateNaissance;
		this.loisir = loisir;
		this.nom = nom;
		this.prenom = prenom;
		this.sexe = sexe;
		this.ville = ville;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateNaissance", nullable = false, length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "loisir", nullable = false, length = 50)
	public String getLoisir() {
		return this.loisir;
	}

	public void setLoisir(String loisir) {
		this.loisir = loisir;
	}

	@Column(name = "nom", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "sexe", nullable = false, length = 10)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	@Column(name = "ville", nullable = false, length = 30)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

}
